config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy] #フォロー機能のルーティングをusersでネストする
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end
  get '/search', to: 'searches#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user #userの子の要素
    belongs_to :book #bookの子の要素
    
    validates :comment, presence: true #commentの内容が空の場合許可しない
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id]) #book_idの一致するものを取得
    comment = current_user.book_comments.new(book_comment_params) #ログインユーザーの情報が入ったコメントを新規作成（ストロングパラメーターあり）
    comment.book_id = book.id #commentのbook_idに取得したidを代入
    comment.save #コメントを保存
    redirect_to request.referer  #遷移元のURLを取得してリダイレクト
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy #idとbook_id両方が一致するコメントを取得して削除
    redirect_to request.referer #遷移元のURLを取得してリダイレクト
  end

  private #フロントエンドからアクセス出来ないようにする

  def book_comment_params #ストロングパラメーター
    params.require(:book_comment).permit(:comment) #book_commentオブジェクトのcommentキーにのみ保存可能にする
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_form.html.erb
<%= form_with(model:[book, book_comment], local: true) do |f| %> <!--book,book_commentに格納するフォームを作成-->
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", class: "w-100" %> <!--コメント入力フォーム-->
  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %> <!--送信ボタンを表示-->
<% end %>

app/views/book_comments/_index.html.erb
<table>
  <tbody>
      <% book.book_comments.each do |book_comment| %> <!--特定ブックのコメントを順番に取り出す-->
      <tr>

        <td>
          <%= link_to user_path(book_comment.user) do %> <!--コメントしたユーザーへのリンクを作成-->
            <%= image_tag book_comment.user.get_profile_image, size: "100x100" %><br> <!--get_profile_imageメソッドで100x100の画像を表示-->
            <%= book_comment.user.name %> <!--ユーザーネームを表示-->
          <% end %>
        </td>
        <td><%= book_comment.comment %></td> <!--コメントを表示-->
        <td>
          <% if book_comment.user == current_user %> <!--もしコメントが現在のログインユーザーのものならば-->
            <%= link_to "Destroy", book_book_comment_path(book, book_comment), method: :delete, class: "btn btn-danger pull-right" %> <!--削除ボタンを表示-->
          <% end %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>