config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy] #フォロー機能のルーティングをusersでネストする
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end
  get '/search', to: 'searches#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User" #followerはuserの子の要素
  belongs_to :followed, class_name: "User" #followedはuserの子の要素
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  before_action :authenticate_user! #ユーザがログインしているかどうかを確認し、ログインしていない場合はユーザをログインページにリダイレクトする。

  def create
    user = User.find(params[:user_id]) #Userモデルからuser_idが一致するものを見つけてuserに代入
    current_user.follow(user) #ログイン中のユーザー情報とフォローするユーザーのidを関連付けてrelationshipモデルにクリエイト
		redirect_to request.referer #遷移元のURLを取得してリダイレクト
  end

  def destroy
    user = User.find(params[:user_id]) #Userモデルからuser_idが一致するものを見つけてuserに代入
    current_user.unfollow(user) #ログイン中のユーザー情報とフォローするユーザーのidが関連付いているデータを探して削除
		redirect_to request.referer #遷移元のURLを取得してリダイレクト
  end

  def followings
    user = User.find(params[:user_id]) #Userモデルからuser_idが一致するものを見つけてuserに代入
		@users = user.followings #userのフォローしている人一覧を@usersに代入
  end

  def followers
    user = User.find(params[:user_id]) #Userモデルからuser_idが一致するものを見つけてuserに代入
		@users = user.followers #userのフォローされている人一覧を@usersに代入
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_btn.html.erb
<% if current_user != user%> <!--現在のユーザーと表示ユーザーが違う場合-->
  <% if current_user.following?(user) %> <!--フォローしているユーザーの場合-->
    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
  <% else %> <!--それ以外の場合-->
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
  <% end %>
<% end %>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %> <!--もしフォローされている人が居る場合-->
  <%= render '/users/index', users: @users %> <!--フォロワー一覧を描画-->
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %> <!--もしフォローしている人が居る場合-->
  <%= render '/users/index', users: @users %> <!--フォロー一覧を描画-->
<% else %>
  <p>ユーザーはいません</p>
<% end %>